title: Chat Wars API Documentation
description: AMQP based API for Chat Wars text MMORPG
remote_theme: alexander-heimbuch/millidocs

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

exclude:
  - README.md

theme: jekyll-theme-midnight